spring:
  application:
    name: jmt
  profiles:
    active: dev
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

spring.jpa.properties.hibernate.format_sql : true
logging:
  level:
    org:
      hibernate:
        type: trace

---
spring:
  profiles: local
  jpa:
    show-sql: true
    properties.hibernate.format-sql: true

#database:
#  datasource-write:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/Product?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true
#    username: root
#    password: root
#  datasource-read:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/Product?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true
#      username: root
#      password: root

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties.hibernate.format-sql: true
#database:
#  datasource-write:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/Product?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true
#      username: root
#      password: root
#  datasource-read:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/Product?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&autoReconnectForPools=true
#      username: root
#      password: root


